# Generated by Django 2.2 on 2021-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_for',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_needed',
            field=models.ManyToManyField(related_name='recipe_for', to='main_app.Ingredient'),
        ),
    ]
